# Generated by Django 5.2.11 on 2026-02-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('rpm', models.FloatField()),
                ('battery', models.FloatField()),
                ('motor_temp', models.FloatField()),
                ('battery_temp', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('faults', models.JSONField(default=list)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_distance', models.FloatField(default=0.0)),
                ('estimated_remaining_km', models.FloatField(default=0.0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('charging_start', models.DateTimeField(blank=True, null=True)),
                ('charging_end', models.DateTimeField(blank=True, null=True)),
                ('charging_gained_percent', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='myapp_telem_timesta_50ea11_idx')],
            },
        ),
    ]
