# Generated by Django 5.2.11 on 2026-02-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetrydata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='telemetrydata',
            name='longitude',
        ),
    ]
