# Generated by Django 5.2.11 on 2026-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_eventlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='telemetrydata',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='telemetrydata',
            name='myapp_telem_timesta_50ea11_idx',
        ),
        migrations.AddField(
            model_name='telemetrydata',
            name='total_daily_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
